### PR TITLE
Responsive UI using CSS Grid

### PR DESCRIPTION
**Pull request by Solksjaer**
* Responsive UI using CSS Grid
* Using localStorage for saving user configuration (Theme, Autorefresh)
* Fix empty device image
* Display devices per type (Switches and Scenes)
* Small JS and HTML warnings fixed

### CODE REVIEW

**Comment by ndg63276** [comment]
Wow, this is awesome. Thanks for correcting so much of my crappy JS, it was my early lockdown project. A couple of minor points:

1. If you log in, then go to another page, and then back to this page, it thinks you are not logged in. The dev console says "No access token", although there is an access token in the user_info object.
2. Should the Theme, Auto Refresh and Refresh buttons be on one line?

**Comment by Solksjaer** [comment]
No problem, glad I found something for the SmartLife on a Browser :)

1. I will check that, but I believe I didn´t change the login logic.
2. I though about that, but had some issues with the jQuery mobile theme. Still I can verify that.

Also didn´t wanted to change that much of the CSS or layout, so that all the other Repos (i.e. Sonos) didn´t seem too different. Maybe they can be merged into a single one? That way any change can be easily updated in a single PR.

**Comment by Solksjaer** [comment]
Login part fixed. Still I found a case where you can login, but you can only get the device list ever 10 minutes. Therefore it will be empty, until you can update the list again.

**Comment by ndg63276** [comment]
Cool, yeah that fixed it. But yes, like you say, you hit the 10 minute limit. Do we need to cache the list of devices in local storage, and just try and update it when you load the page? (I'm happy to try if you don't want to)

**Comment by Solksjaer** [comment]
Exactly, was thinking about moving all references of `user_info` to `localStorage.user_info`. Also checking at the beginning so that the cookie login  doesn´t remove the list for this 10 min period.

**Comment by Solksjaer** [comment]
Looks like this should work.
Can you check it out?

**Comment by ndg63276** [comment]
Looks great. I've uploaded it to smartathome.co.uk. Thanks!

**Comment by Solksjaer** [comment]
Awesome!

**Pull request merged**
