### PR TITLE
Cors enabled servers

### PR DESCRIPTION
**Pull request by Beat-YT**
the eu server and the us server have cors support

### CODE REVIEW

**Comment by Beat-YT** [comment]
@ndg63276

**Comment by ndg63276** [comment]
Yeah looks good, I'm in the EU so I can only test that server. How did you find out that they have CORS enabled? Do you know that the CN server doesn't?

**Comment by Beat-YT** [comment]
I have postman and when I do request to US and EU, it have cors headers, so it doesn't need to go throught the proxy.

However, tuyacn doesn't.

**Comment by Beat-YT** [comment]
EU and US include the following headers : `Access-Control-Allow-Origin: *` which mean it allow any website. However, CN doesn't include that header

**Pull request merged**
